# Generated by Django 4.2.3 on 2023-07-18 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('body', models.TextField(max_length=600, verbose_name='Текс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['theme'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=150, verbose_name='Название')),
                ('date_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки')),
                ('date_end_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=63, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Завершена', max_length=63, verbose_name='Статус рассылки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_work.messages', verbose_name='Письмо для рассылки')),
                ('user_name', models.ManyToManyField(to='my_work.client', verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<function now at 0x7f4ab97ea840>', max_length=100, verbose_name='Название')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('status', models.CharField(max_length=50, verbose_name='Статус попытки')),
                ('answer', models.TextField(default=None, max_length=600, verbose_name='Ответ с сервера')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_work.setting', verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-date_last'],
            },
        ),
    ]
