# Generated by Django 4.2.3 on 2023-07-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0002_messages_alter_client_options_setting_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f78957ea840>', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='periodicity',
            field=models.CharField(choices=[('Раз в минуту', 'Раз в минуту'), ('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=63, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Создана', max_length=63, verbose_name='Статус рассылки'),
        ),
    ]
