# Generated by Django 4.2.3 on 2023-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0005_alter_logs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7fc9e4fc2840>', max_length=100, verbose_name='Название'),
        ),
    ]
